### PR TITLE
create DisciplineFSuite #528

### PR DESCRIPTION
**Pull request by bwiercinski**
https://github.com/disneystreaming/weaver-test/issues/528

### CODE REVIEW

**Comment by Baccata** [comment]
I think it's good. Let's see how it looks like in tests 😄

**Comment by bwiercinski** [comment]
@Baccata can you check it out. i was managed to implement it using `RunnableSuite`. it works well both in sbt and in intellij, but with that price I had to reimplement `WeaverRunner`. now `testDescriptions` is evaluated each time instead of lazy val. are you ok with that?

if it is ok I will fix JS tests. or maybe you have more clever idea

**Comment by Baccata** [comment]
@bwiercinski , mmm, I'm gonna have to give it a think. I'll get back to you next week

**Comment by bwiercinski** [comment]
did you run it? is reevaluating testDescriptions each time a big problem? maybe you know better edgecases using junit api with intellij

**Comment by Baccata** [comment]
> maybe you know better edgecases using junit api with intellij

I'm actually not certain ... did you try to run a DisciplineF spec with Intellij ? If you could provide a screen capture to see what it looks like, that'd be great, with several tests/rule sets being tested.  (assuming you're an Intellij user, which I'm not, and I've uninstalled Intellij a while ago, would rather not have to download it again).

**Comment by bwiercinski** [comment]
as they are evaluated they appearing on the GUI, firstly **1 of 1 tests passed**, then 2/2 and so on. they appear in the order as they are computed, but i can easily sort them by name by using a button. not best but looks good.
image

using sbt:
image

non discipline tests are working as usual
image

**Comment by Baccata** [comment]
Okay, I **think** it's good enough for me. Proceed with some tests ^^

**Comment by bwiercinski** [comment]
all passed :)

**Comment by Baccata** [comment]
Thanks @bwiercinski, I'm not forgetting you, I've just been incredibly busy. I'll review later this week

**Review by Baccata — APPROVED** [review]

**Comment by Baccata** [comment]
Thanks for this !

**Comment by bwiercinski** [comment]
thanks :) , when you will release it?

**Comment by Baccata** [comment]
On its way : https://github.com/disneystreaming/weaver-test/releases/tag/v0.6.14

**Comment by bwiercinski** [comment]
i screwed up when using synchronized. monitors used on synchronized are `var`s and eventually synchronization doesn't work. it only matters when using intellij. i will make a new PR with a fix

**Pull request merged**
