### PR TITLE
DisciplineFSuite: fix race condition

### PR DESCRIPTION
**Pull request by bwiercinski**
use constant monitors when using synchronized

quick followup of https://github.com/disneystreaming/weaver-test/pull/548

(friday, friday, friday)

### CODE REVIEW

**Review by Baccata — APPROVED** [review]

**Comment by Baccata** [comment]
We're having issues with sonatype, I won't release this patch straight away as I need time to investigate a little

**Comment by bwiercinski** [comment]
any updates?

**Comment by Baccata** [comment]
Thanks for reminding me. Looks like 0.6.14 has successfully made its way to central though the CI was failing. Probably a red-herring of some sort. 

Absent any other information, I've triggered 0.6.15 : https://github.com/disneystreaming/weaver-test/releases/tag/v0.6.15, we'll see how it goes.

**Comment by bwiercinski** [comment]
i'm not seeing it https://mvnrepository.com/artifact/com.disneystreaming/weaver-cats-core_2.13

**Comment by Baccata** [comment]
I had to re-trigger the job cause it failed and I had missed the notif. 

Anyway, it's definitely here now : 

Screenshot 2022-08-10 at 17 03 25

**Pull request merged**
