### PR TITLE
Addressing #639: print stacktrace in logs

### PR DESCRIPTION
**Pull request by henryxparker**
This is a quick and dirty fix for [the weaver.Log not printing stack traces](https://github.com/disneystreaming/weaver-test/issues/639). 
I didn't see any tests for the core module so I didn't write any.
Any feedback appreciated

### CODE REVIEW

**Comment by henryxparker** [comment]
I don't know why the cla assistant has two comments. Let me know if that is a blocker and what to do about it

**Comment by henryxparker** [comment]
Sorry for the long wait. I was laid off for a while and totally forgot that I had made this PR. 
Now that everything is settled I'll be working on it again

**Comment by Baccata** [comment]
@henryxparker thanks for taking the time to come back to this PR ! 

However, weaver is in the process of being moved to the typelevel organisation, and though I cannot attest to when exactly the move will conclude, it's quite unlikely that I'll issue another release of weaver under the disneystreaming organisation. If it's not too much to ask, I would suggest moving your PR over there. 

https://github.com/typelevel/weaver-test

**Comment by henryxparker** [comment]
Oh sweet, I'll add it there. Could you add something to the README to indicate this move?

**Pull request closed without merging**
