### PR TITLE
Build monix module with scala 3

### PR DESCRIPTION
**Pull request by lukestephenson**
Previous attempt only built monix-core.  Part of #434

### CODE REVIEW

**Comment by Baccata** [comment]
doh, my bad, should have caught it. Whilst you're at it, would you mind enabling it on the monix-bio as well ?

**Comment by lukestephenson** [comment]
ok.  I'll add monix-bio as well

**Review by Baccata — APPROVED** [review]
Waiting for CI to be green and I'll merge/release

**Comment by Baccata** [comment]
Oh well, couldn't have been that simple. @lukestephenson don't worry about it, I'll take that over

**Comment by lukestephenson** [comment]
@Baccata I know how to fix. I'm just not sure what command to run to get this project verifying all scala versions from sbt locally, so relying on CI for slow feedback.

**Comment by lukestephenson** [comment]
What's the best command(s) to run locally before pushing changes?

**Comment by Baccata** [comment]
The build is huge, so it really depends on what you're touching, but in this, the following would be sufficient : 

```
> scalafmtAll 
> scalafix 
> monix3/test 
> monixBIO3/test 
```

If you're not scare of using a lot of CPU, the following will run what the CI runs : 

```
> ci 
```

**Comment by Baccata** [comment]
>  I'm just not sure what command to run to get this project verifying all scala versions from sbt locally

Yeah that's an annoying point of using SBT for complex projects. In particular, we're cross-compiling everything that can be against cats-effect-2 and cats-effect-3, whilst the ecosystem and users are transitioning (we didn't want to maintain separate branches). So we've been using [project-matrix](https://github.com/sbt/sbt-projectmatrix) to allow for it, but it makes it hard to say "test all axis of this particular project", or "test js on all projects that have it"

**Comment by lukestephenson** [comment]
I suspect the monix-bio tests are hanging now. It's taking a lot longer than previous CI builds to execute the tests.

**Comment by Baccata** [comment]
@lukestephenson I don't want to block the release of monix for Scala 3 for you if the addition of monixbio is a puzzle 😞 . If you open a PR with just the first commit from this branch, I'll merge and release and find some time this week to look into why monix-bio is hanging

**Comment by lukestephenson** [comment]
locally both `monix3/test` and `monixBio3/test` are hanging.

seeing the following errors before it hangs.
```
[info] weaver.monixcompat.TaskSuiteTest
java.lang.NoClassDefFoundError: sbt/testing/Status$
  | => mat weaver.monixcompat.TaskSuiteTest$.$init$$$anonfun$8$$anonfun$2(TaskSuiteTest.scala:43)
	at monix.eval.Task$Map.apply(Task.scala:4727)
	at monix.eval.Task$Map.apply(Task.scala:4726)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:189)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
	at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:118)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.startLoop$$anonfun$1(TrampolineExecutionContext.scala:142)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.startLoop(TrampolineExecutionContext.scala:143)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:40)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:57)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:36)
	at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:35)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:72)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:184)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
	at monix.eval.internal.TaskExecuteOn$$anon$1.run(TaskExecuteOn.scala:71)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: sbt.testing.Status$
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 28 more
```

**Comment by Baccata** [comment]
Huh, alright. Looking into it now

**Comment by lukestephenson** [comment]
I've just tried a fix for the ClassNotFoundException.  Appears to be a Scala 3 issue.

**Comment by Baccata** [comment]
Cool, I reached the same conclusion and am happy with your fix. I'll prepping a repro for the Scala 3 maintainers

**Comment by lukestephenson** [comment]
ok.  the build is passing.  Thanks for the help @Baccata .  I'm signing off for the night

**Comment by Baccata** [comment]
Thanks for this, I'll release the next version right away. Have a good night !

**Comment by Baccata** [comment]
It's actually a [bug in the expecty library](https://github.com/eed3si9n/expecty/issues/59) (which we use to provide fluent assertions in weaver).

**Pull request merged**
